добавлен shared preference
LukianBat/HeartOracleSportStudent pull request #1
Opened 2019-09-07 13:02 UTC by LukianBat

Сева сюда

2019-09-07 14:48 UTC, SevaZhukov requested changes

2019-09-07 14:48 UTC, SevaZhukov commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
Перейти на Kotlin dsl

2019-09-07 14:48 UTC, SevaZhukov commented on app/src/main/java/com/heartoracle/sport/student/core/App.kt
> +
Лишний отступ

2019-09-07 14:48 UTC, SevaZhukov commented on app/src/main/java/com/heartoracle/sport/student/core/dagger/module/ApplicationModule.kt
> +
Лишние отступы

2019-09-07 15:15 UTC, SevaZhukov requested changes

2019-09-07 15:15 UTC, SevaZhukov commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
Вынести все в версии, пример смотри на урбанист парковка

2019-09-07 15:15 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/dagger/module/PreferenceModule.kt
> +class PreferenceModule {
Судя по названию модуля он должен провайдить только преференсы

2019-09-07 15:15 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/data/PreferenceDataSource.kt
> +class PreferenceDataSource @Inject constructor(context: Context) {
в датасорсе не должны создаваться преференсы, тк они могут юзаться в каком-то еще датасорсе и их придется создавать снова, поэтому сюда стоит передавать уже преференсы

2019-09-07 15:15 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/data/PreferenceDataSource.kt
> +    fun getNumber(): Int = preferences.getInt(NUMBER_KEY, NUMBER_DEFAULT)
сделай не функцию, а переменную c методами set get
`val number: Int
get() = preferences.getInt(NUMBER_KEY, NUMBER_DEFAULT)
set() {
preferences.edit().putInt(NUMBER_KEY, number).apply()
}`

2019-09-07 15:15 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/domain/repository/PreferenceRepositoryImpl.kt
> +        } else throw Exception()
здесь не стоит выбрасывать exception. Есть смысл сделать тип нулабельным в датасорсе и нул будет означать что значение не задано， в репо не должно быть никакой инфы о дефолтном значении датасорса

2019-09-07 15:15 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/domain/usecase/get/GetUseCase.kt
> +interface GetUseCase<T> {
название интерфейса слишком общее. Лучше GetNumberUseCase, а реализацию GetNumberUseCaseImpl

2019-09-07 15:15 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/domain/usecase/set/SetNumberUseCase.kt
> +class SetNumberUseCase @Inject constructor(private val repository: PreferenceRepository) :
все то же самое что я описал про юзкейс гет

2019-09-07 15:25 UTC, SevaZhukov requested changes

2019-09-07 15:25 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/presentation/BaseViewModel.kt
> +abstract class BaseViewModel {
почему ты решил не наследоваться от гугловой?

2019-09-07 15:25 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/splash/di/SplashModule.kt
> +class SplashModule {
зачем для сплэша модуль и получение значения из памяти? сплэш нужен исключительно для красивой загрузки приложения и не должен ничего выполнять кроме отображения заглушки

2019-09-07 15:25 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/splash/presentation/SplashActivity.kt
> +class SplashActivity : BaseActivity<ActivitySplashBinding>() {
простые активити типа сплэша не стоит наследовать от базовой, тк им не нужна вьюмодель

2019-09-07 15:25 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/splash/presentation/SplashViewModel.kt
> +class SplashViewModel @Inject constructor(private val useCase: GetUseCase<Int>) : BaseViewModel() {
выпилить))

2019-09-07 15:25 UTC, MrSwimmer commented on app/src/main/res/layout/activity_splash.xml
> +            app:layout_constraintLeft_toLeftOf="parent"
заменить на layout_constraintStart_toStartOf

2019-09-07 15:25 UTC, MrSwimmer commented on app/src/main/res/layout/activity_splash.xml
> +            app:layout_constraintLeft_toLeftOf="parent"
Right -> End

2019-09-07 15:25 UTC, MrSwimmer commented on build.gradle
> +
отступ))

2019-09-09 09:13 UTC, NSKgooner commented on app/src/main/java/com/heartoracle/sport/student/feature/splash/presentation/SplashViewModel.kt
> +class SplashViewModel @Inject constructor(private val useCase: GetUseCase<Int>) : BaseViewModel() {
))

2019-09-09 09:13 UTC, NSKgooner commented on build.gradle
> +
))

2019-09-11 14:20 UTC, SevaZhukov requested changes

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/core/dagger/module/ApplicationModule.kt
> +        NumberDataSourceModule::class,
это не должно быть в коре, это должно подключаться только в те фичи в которых это юзается, даже если сейчас это юзается во всех фичах

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/settings/data/datasource/dagger/NumberDataSourceModule.kt
> +
отступ

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/settings/data/repository/NumberRepository.kt
> +
отступ

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/settings/data/repository/NumberRepository.kt
> +interface NumberRepository {
интерфейс пишется выше реализации

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/settings/domain/usecase/get/GetNumberUseCase.kt
> +interface GetNumberUseCase {
интерфейс пишется выше реализации

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/java/com/heartoracle/sport/student/feature/settings/domain/usecase/set/SetNumberUseCase.kt
> +interface SetNumberUseCase {
интерфейс пишется выше реализации

2019-09-11 14:20 UTC, MrSwimmer commented on app/src/main/res/layout/activity_settings.xml
> +            android:text="@={viewModel.number}"
зочем двусторонний биндинг?

2019-09-11 14:55 UTC, merged